### ISSUE TITLE
Request: page preview before publishing

### ISSUE THREAD

**Issue by Joduai** [bludit/bludit#1005]
Pretty much as the forum topic states: https://forum.bludit.org/viewtopic.php?p=6558
Would be great to get a possibility to preview the post/page during its creation process.
Editor's preview mode aren't sufficient in this matter.

**Comment by SamBrishes** [comment]
Hellow,

Since I'm hosting my own Bludit website I noticed that this feature is REALLY important. I don't know when Diego adds a core solution, but for the meantime I wrote a small plugin:

https://github.com/pytesNET/draft

It has been written really fast, so I hope it works seamless. But at least I couldn'T mention any issue during the use on my website. :D  

Sincerely,
Sam.

**Comment by Joduai** [comment]
@SamBrishes Diego implemented page previews couple days ago.
I already updated my instance but instead of seeing page I get 404 :expressionless:
Hadn't trace the problem. I just need to get a testing env, as updating production site and fixing bugs isn't that easy as I supposed.

If you try latest updates let me know if preview mode is working. Would be great to know if it works under php 7.2

**Comment by SamBrishes** [comment]
Hellow,

thanks, didn't know that this feature is already implemented. :D 

I'll try it out, if it works on my environment.

Sincerely,
Sam.

**Comment by dignajar** [comment]
Hi, the code I push to GitHub is not 100% tested so you can have some errors, but this features is going to be included for Bludit v3.9

**Comment by dignajar** [comment]
Implemented in Bludit v3.9.0 beta 1. Regards
