### ISSUE TITLE
[CORE] Image library

### ISSUE THREAD

**Issue by dignajar** [bludit/bludit#1016]
I would like to improve the image library. Recommendations are welcome.
Also, would be better to work with the image at the browser level (JavaScript) or in the server side (PHP) ?

**Comment by Joduai** [comment]
What do you exactly mean by "image library"?
 
Generally the only 3 features end user gets in bludit to operate on images are 
- uploading images per post (or globally if he finds this option in config file)
- set the img as cover
- insert img inside post

He has no way to operate on thumbnails, although he can set the size of thumbnail in options.
Even advanced user has problems with finding the right path, because unique post ID is nowhere shown in /admin.

What I personally think that would ease up managing the images would be:
- creation of 2-3 different size thumbnails / backend
  (should all need to be created and stored upon upload, or created on the fly and stored temporarily?) 
- ability to create a custom thumbnail / frontend
  There's a nicely working https://github.com/tapmodo/Jcrop
- something like a foldable textarea window for image containing:
  - relative URI to original image
  - html img link 
  - same as above to thumbnail
  - thumbnail img link to full sized img
- select boxes allowing to insert more than 1 image at once
  Maybe along with a dropdown to choose what type to insert (thumg, fill img etc, as mentioned above in textarea links)
- maybe watermark option.
  Something like a hotlink protection based on referer, where images linked from other websites could be generated with a watermark (for example a bottom bar with website address)
- this has already been asked but an advanced media manager to operate globally on images along with nested directories would be great. Especially for managing galleries, and still allowing to reuse images instead of uploading them per post. Of course user can enable the global img directory, but having like 200 images in 1 flat dir slows down all operations, and makes it difficult to handle.
But this is more related to bludit's features, not only to images.

I'm not sure if such options you had on mind.

**Comment by BlakesHeaven** [comment]
It might just be worth looking through all the current image related issues/suggestions:
- #949 [ENHANCEMENT] Images relative to the parent post
- #983 Feature Request: Upload images to your plugins database/content
- #898 [PLUGIN] Thumbnails in OpenGraph and Twitter Cards
- #1009 API: Upload image
- #992 [Suggestions] quickly add multiple pictures
- #988 user profile image compression/cropping/filename
- #983 Feature Request: Upload images to your plugins database/content
- #713 [CORE] [Media Manager] Create different size of images after uploading an image
- #695 [PLUGIN] Image Comparison Slider

**Comment by dignajar** [comment]
I was thinking to manipulate images, like resize, compress. Maybe if exits some library in JavaScript would be good to do this process in the user side and not in the server.

About the Media manager, yes is true its need to be improved and all the point you mention are right, but I don't want to over complicate.

**Comment by Joduai** [comment]
Long time ago I was looking for a way to resize and compress img in frontend (probably with jquery), but it had too many caveats. But from quite some time most popular browser support html5 canvas toblob()
Since it offers to manipulate img object in a safe way I peeked out of curiosity - while I was tied with other flatfile cms - if there are any projects using it. Just to mention two
https://github.com/fengyuanchen/compressorjs
https://github.com/nodeca/pica

Pica describes all the caveats in readme. 
However I've never seen this method being used in any CMS when it goes to processing images, and I don't feel that not leaving a fallback (serverside) method would be reasonable.

**Comment by dignajar** [comment]
I'm working to store the images for each page in the page name but is quite hard, I mean here `bl-content/uploads/pages/<KEY>/`.

The page `key` doesn't exits until the user save the page, that why I use the UUID which exists in the first moment.

I did some workaround to use the `UUID` and then rename to the `key`, but I need to parse the content also, because the user can insert the image and the first time the image has the URL `bl-content/uploads/pages/<UUID>`.

**Comment by dignajar** [comment]
I will create a symlink to find faster the image upload directory.

**Comment by dignajar** [comment]
I was checking this library and looks really good.
https://github.com/fengyuanchen/compressorjs

**Comment by BlakesHeaven** [comment]
Regarding:
> I'm working to store the images for each page in the page name but is quite hard, I mean here `bl-content/uploads/pages/<KEY>/`.

Can I suggest considering, instead of `/pages/<key>` do `/pages/<title>`

Benefit: Is human readable for back end work.
Con: Title may change so  may need to update `/pages/<title>` folder.

**Comment by BlakesHeaven** [comment]
Please show image location settings in Admin, along with `relative to` setting.for easy update instead of being hidden..
I'll  raise seperate issue for your easy tracking 🙂

**Comment by dignajar** [comment]
Bludit now creates the symlink `/pages/<title>`, but still keep the original `/pages/<key>`.
