### ISSUE TITLE
[Roadmap] Bludit v4

### ISSUE THREAD

**Issue by dignajar** [bludit/bludit#1057]
Features I would like to implement for Bludit v4. I will add more with the time.

- Theme settings: Allow to the user after enabling the theme setup different parameters, similar to the settings for plugins.
- Auto Updates: The user can update Bludit from the admin panel.
- Plugins installer: Check the official database of plugins and allow the user to download and install plugins from the admin panel, also support updates.
- Themes installer: Similar to the plugins installer but for themes.
- Page type `Private`: Show on homepage only for members and access only for members.
- Page type `Unlink`: Not listed on homepage and access only to who has the link.
- [Custom fields](https://github.com/bludit/bludit/issues/895)

**Comment by Joduai** [comment]
Got three things to ask/propose:
1. Will you allow to set the parent for all page types?

2. Is it going to be possible to set a specific page to list all blog entries?
Currently it is very confusing to do it and it's not working as I supposed. Namely I can set a static page as index page, but all other pages (no matter their type) start with url set in pages field in url filter.

3. actions in page management doesn't fit in one line. Shouldn't there be an option to switch between text buttons and only icons? 

4. As it goes to actions, deleting couple pages at once is impossible (for example all autosaved pages). I almost deleted couple times pages, because deleting an entry reloads the management page and shows the "pages" tab. Would be great to load the last tab after deleting a page.   

5. I sometimes need to enable error reporting. Doing it from within CMS would come in handy, for example as a switch in "about" page. This would be also a good thing for those non technical users who get errors but nobody can help them without seeing what's going on.

**Comment by BlakesHeaven** [comment]
Would you please list existing #issues that are likely to be included?
There are many from long ago that should maybe be included.

**Comment by SamBrishes** [comment]
Hellow

I've also a bunch of things / suggestion to ask :D

1. It would be REALLY awesome to manage the "custom" fields array of the Page DB on the backend too. So just `key => value` text fields to adapt them on the respective page would be a great help.

2. An extended role -> permission system (or API) with custom roles, and an adaptable permission-set would be a dream.

3. Instead of adding new (static-written) page types, it would be highly comfortable using a PageType API. So that everyone can also create their own types (I know, it's similar to point 2)

4.  An extended backend theme API, which allows creating custom admin pages with own URL routes (next to the default plugin configuration page). I'm using a small Hack on my [Snicker](https://github.com/pytesNET/snicker/blob/ae0b8042db0139eb7eb18d6cb44fab8835738bf7/plugin.php#L756) and [Designer](https://github.com/pytesNET/designer/blob/967a8b634ccb75eb74e83fff567645936078572e/plugin.php#L384) plugins, but it would be really cool to do it without REGEX-ing the page content :D 

5. Sorry, as vanilla JS developer I need to ask this too... **no jQuery**. (I also can help convert existing scripts into Vanilla JS, if help is needed).

Thanks for your great work and your awesome product.

Sincerely,
Sam.

**Comment by clickwork-git** [comment]
>     * Page type `Private`: Not listed and access allowed only to the owner of the page.

I think, it has to be defined who has access to the content. I would prefer a "member".

**Comment by Bayerberg** [comment]
If I can just put in my two pennies worth:

- 1. Custom fields for pages
 Either in theme configuration or globally, would be easy to integrate this into plugins.  
- 2. Vanilla JS / JQuery toggle. 
Usually I run vanilla, theres no reason to load up unnecessary libraries 
- 3. Extensions - a way of customising Bludit to suit bloggers/ marketers/ growth hackers by tailoring the experience to their needs. Think of plugins on steroids - see this topic https://forum.bludit.org/viewtopic.php?f=6&t=1210 
- 4. Admin themes 
its a pain to do one, would be nice to get this debootstrapped and enable users to pick which one they like exactly as site themes. 

General tweaks
No bootstrap - Bludit needs its own front-end skeleton to run on. General UI, clean UX, iconography made to handle not only the main features but custom plugins as well. I can do it, poke me on twitter.   
Cleanup - there are still references to blog pages.

**Comment by spencerthayer** [comment]
I would like to see all this too:
> It would be REALLY awesome to manage the "custom" fields array of the Page DB on the backend too. So just key => value text fields to adapt them on the respective page would be a great help.
> An extended role -> permission system (or API) with custom roles, and an adaptable permission-set would be a dream.
> Instead of adding new (static-written) page types, it would be highly comfortable using a PageType API. So that everyone can also create their own types (I know, it's similar to point 2)

**Comment by hxii** [comment]
Same as the comment above, and the quoted comment before it, I think post meta/custom fields are a very useful feature.

**Comment by dignajar** [comment]
Hi, I have been working on `custom fields`, you can get some information about it here.
https://github.com/bludit/bludit/issues/895

**Comment by dimobelov** [comment]
Maybe in version 4 is not bad to have some basic email function (bl_mail). Now every plugin with mailing functionality use its own solution. Some standardized way to send email will help a lot. In Settings we can set using **php mail** or **smtp data**.

**Comment by anaggh** [comment]
These 3 features could be part of a single core plugin like `Package Manager`. We should also deprecate `Version` plugin if this happens.

* Auto Updates: The user can update Bludit from the admin panel.
* Plugins installer: Check the official database of plugins and allow the user download and install plugins from the admin panel, also support updates.
* Themes installer: Similar to the plugins installer but for themes.

**Comment by philippd1** [comment]
> These 3 features could be part of a single core plugin like `Package Manager`. We should also deprecate `Version` plugin if this happens.
> 
> * Auto Updates: The user can update Bludit from the admin panel.
> * Plugins installer: Check the official database of plugins and allow the user download and install plugins from the admin panel, also support updates.
> * Themes installer: Similar to the plugins installer but for themes.

@anaggh great idea 😎
I already wrote the plugins
- [theme-download](https://github.com/philippd1/bludit-theme-download)
- [theme-uninstaller](https://github.com/philippd1/bludit-theme-uninstaller)
- [plugin-download](https://github.com/philippd1/bludit-plugin-download)
- [plugin-uninstaller](https://github.com/philippd1/bludit-plugin-uninstaller)

today I released `v2.0.0` of [auto-update](https://github.com/philippd1/bludit-auto-update) which works really fast and completely in the background with current progress states.

so...
should I write a plugin that combines all of the functions above into one?
what do you think? @dignajar

**Comment by dignajar** [comment]
@philippd1 Hi, it could be a good idea to combine all together but not sure because of the development and debug.

**Comment by philippd1** [comment]
![image](https://user-images.githubusercontent.com/17651032/74732274-2b8deb00-524a-11ea-82d3-e567c9de54f9.png)
@dignajar yeah, I'm currently giving it a shot, looking something along those lines ⬆

**Comment by Kazem-ma79** [comment]
Please add custom hook support for plugins in next version.

**Comment by hide-me** [comment]
How are you with the development of version **4**?

**Comment by dignajar** [comment]
I'm currently a little off in the project but I'm still working on Bludit don't worry; almost all the features are covered by plugins for the moment, also my idea is to move everything to plugins and keep Bludit as a small core for CMS.

**Comment by Kazem-ma79** [comment]
> I'm currently a little off in the project but I'm still working on Bludit don't worry; almost all the features are covered by plugins for the moment, also my idea is to move everything to plugins and keep Bludit as a small core for CMS.

Please allow plugins to use their own hooks (defined by plugin developer), so it would be very easier to manage CMS using plugins.
Also it would be better to make a section for changing dashboard theme.
Thanks for your great project.

**Comment by dignajar** [comment]
@Kazem-ma79 can you give me some details about own hooks ? because the hooks are execute in different parts of the themes, for example at the beginning of a page, at the bottom of a page, so if you create custom hooks where do you think they going to be executed?

**Comment by philippd1** [comment]
@Kazem-ma79 concerning the idea of a dedicated section for admin-theming: there's already been a discussion on the issue thread #987 😉


> my idea is to move everything to plugins and keep Bludit as a small core for CMS.

@dignajar highly appreciate that you favor the simplicity and modularity 👍
is the "AIO-Manager" plugin for theme and plugin installation still relevant? would like to continue working on it if it's still relevant for Bludit Core
(UX for plugin and theme installation would be much nicer with an actual UI :) )

**Comment by SamBrishes** [comment]
What do you think about a file-extension associated Markup rendering instead of forcing Markdown completely?

## For a better Understanding
For example: We add a small new `RenderContent` interface / class, which allows plugins to "add" a Markup library (Markdown, textile, ...) next to some information such as the associated file extensions (so `.md` / `.markdown` on Markdown Files, `.textile` on Textile files, and so on...). 

Now, when the content of a page gets rendered (using `$page->content()`), the filepath of the respective page gets passed to the new interface, which calls the added markup library according to the file extension which returns the rendered content.

## Advantages
- Bludit becomes multi-lingual on the Markup languages
- The user is able to use multiple markup languages side-by-side
- Parsedown and other libraries are just added as plugin and better maintainable

## Reason
Markdown is a good way to go and maybe perfect for the most people using Bludit, but sometimes a more extensive markup language would be awesome (such as textile).

I know that you're able to disable the Markdown rendering at all, but a core solution to support multiple markup languages next to each other would be a better solution.

**Comment by SavaAlexandruStefan** [comment]
Hello,

What about the ability to insert a static page into the main menu with all it's subpages as a dropdown ?

**Comment by Joduai** [comment]
Any changelog for v4.0.0 A1?

**Comment by ctuxboy** [comment]
Suggestions: Adding filters in Dashboard -> Manage -> content:

  - Filter content in the dashboard by title, categories, tags

  - Option/filter: show only parent pages and when click on a parent-page shows the related child-pages (now it is very confusing manage the content, without filters, if there are a lot of parent/child-pages.
  -  Adding search-function that also search the content (not only titles), similar the front-end search-plugin.

**Comment by BlakesHeaven** [comment]
Can we have more settings in Admin to 

> Turn off Notifications panel
> option to control how many notification are displayed
> where images are stored, eg in root or by page
