### ISSUE TITLE
Deleting cover image

### ISSUE THREAD

**Issue by clickwork-git** [bludit/bludit#1060]
If an image used as cover image is deleted from the tab "Images", there is still a link to the no longer existing image (it can only be deleted from from "Options" > "General" > "Cover Image").

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
