### ISSUE TITLE
[REQUEST] Option to Insert Thumbnail Image

### ISSUE THREAD

**Issue by BlakesHeaven** [bludit/bludit#1069]
### Describe your problem
I make frequent use of the image Thumbnails in posts and would like an easier way to insert the thumbnails.
### Steps to reproduce the problem
1.  Open Content and click `Image`
2. Right-click on the thumbnail of the image you want to use
3. Click `Insert` to place the large image in place.
4. Edit the image URL by replacing with what we copied in step 2

### What I want
A button added, saying `Insert Thumbnail`

[_BTW I tried inserting an image to this issue but it is never allowed_ :-1:  ]
### Bludit version
All

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
