### ISSUE TITLE
Add index for tags/categories

### ISSUE THREAD

**Issue by DivineDominion** [bludit/bludit#1076]
### Describe your problem

When a tag's URL is e.g. `example.com/tag/the-tag`, this lists all posts with `the-tag`; the parent URL path component will be a 404 Not Found: `example.com/tag`

There is currently no way to display a list of all tags from the database. Neither a category index.

Both `$tags->keys()` and `$categories->keys()` can return a list of known tags and categories, respectively.

But as of now, Bludit aborts with a 404 for the expected `/tag` index for 2 reasons:

1. Either it [aborts with a 404 early](https://github.com/bludit/bludit/blob/master/bl-kernel/url.class.php#L59) when the URL slug is `/tag` (i.e. the tag prefix without a trailing slash), or
2. it tries to fetch a list of pages with the tag `''` (empty string), which fails and sets the page to 404/not found as well, but at a later point.

### Bludit version

v3.9.2

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
