### ISSUE TITLE
Pagination broken on Admin Content Management

### ISSUE THREAD

**Issue by BlakesHeaven** [bludit/bludit#1087]
### Describe your problem
No content is displayed when first visiting content Management, until the next/last button is clicked. Then all are displayed.
![20190927_183710](https://user-images.githubusercontent.com/37149377/65789873-338fa600-e156-11e9-9da5-5ec8a54a6aa5.jpg)
![20190927_183626](https://user-images.githubusercontent.com/37149377/65789914-499d6680-e156-11e9-8f62-ad163722bd05.jpg)

### Steps to reproduce the problem
Add about 10 parent pages or more, each with  about 6  child pages.

### Bludit version
V3.9.2.

I would expect it to at least show pages on first pages and break after x pages regardless of parent/child.
I would hope the parent would be repeated as continued on the next page if child pages go onto next page.

**Comment by BlakesHeaven** [comment]
Same issue exists in v3.10.0

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
