### ISSUE TITLE
Improve PageSpeed and YSlow ratings by compressing and joining CSS files and JS Files

### ISSUE THREAD

**Issue by machadoug** [bludit/bludit#1101]
Since all CSS files are render blocking by default it is essential to have the least amount of css files possible. It would be awesome if bludit had a feature for template developers to compress and join files. Putting all of your CSS into one file substantially reduces the amount of time it takes to load your web pages because you are reducing the amount of things the web browser has to load before displaying your page.

The same goes for Javascript files.

Minimizing the HTML output would also be great.

**Comment by hxii** [comment]
My personal opinion is this hardly an issue but more of a plugin request. If anything, it's up to you as the template designer to optimize, compress and minify your sources.
For instance, WordPress does not do this either.

**Comment by dignajar** [comment]
I feel this request is more for the developers of themes.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
