### ISSUE TITLE
[REQUEST][PLUGIN/CORE][WIP] Bludit Manager Plugin

### ISSUE THREAD

**Issue by philippdormann** [bludit/bludit#1140]
decided to open an extra issue for this to reference all stuff regarding this plugin @dignajar 

# AIO Manager plugin
currently working on this, as discussed in #1057 + #1139
also, see #658

assigning this issue to myself.
it's currently looking like this:

## All
![image](https://user-images.githubusercontent.com/17651032/74788529-4b58f980-52b2-11ea-9c35-b6a1cbae25a8.png)

## Themes
![image](https://user-images.githubusercontent.com/17651032/74788385-eb625300-52b1-11ea-842f-608d70f5715f.png)

**Comment by philippd1** [comment]
as of now, this is working:
- Bludit updates
- Plugin Installation
- Theme Installation

TODO:
- Plugin Removal
- Theme Removal
- Plugin Updates
- Theme Updates

**Comment by philippd1** [comment]
update:
> as of now, this is working:
> 
> * Bludit updates
> * Plugin Installation
> * Theme Installation
> * Plugin Removal
> * Theme Removal
---
> TODO:
> 
> * Plugin Removal
> * Theme Removal

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
