### ISSUE TITLE
Bludit api CORS doesn't seem to work with cross domains. 

### ISSUE THREAD

**Issue by ronaldaug** [bludit/bludit#1142]
### Describe your problem
Although header is allowed [here](https://github.com/bludit/bludit/blob/2e2b5a179ad1029e349f619afad7fe304ff2183a/bl-plugins/api/plugin.php#L284) as "*",
CORS doesn't seem to work with cross domains. 

### Steps to reproduce the problem
Set up two domains with SSL and retrieve content via API.

### Screenshot 
<img width="600" alt="Screen Shot 2020-02-23 at 9 44 43 PM" src="https://user-images.githubusercontent.com/33022876/75114603-d573da00-5685-11ea-8ee1-927ac56c9c05.png">

### Bludit version
3.11.0

### PHP version
7.3

### Dev environment
OS - Mac 
Server - Xampp Apache with virtual host (I've also tested with **.com** domains)

**Comment by dignajar** [comment]
Hi,
the CORS are enabled by the webserver and the sometimes also in the browser you need to allow it. You need to configure the webserver to support cross domains.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
