### ISSUE TITLE
Plugin Static Pages: child pages are sorted wrong

### ISSUE THREAD

**Issue by clickwork-git** [bludit/bludit#1148]
Child pages are sorted wrong by the plugin Static Pages.

### Bludit version
3.11

**Comment by BlakesHeaven** [comment]
Hi, if there is some changes to make in this area, can  #935 be considered?
Thanks.

**Comment by andilge** [comment]
here +info for reproduction
https://cdn.discordapp.com/attachments/944963992747655188/945295097594019891/unknown.png

**Comment by andilge** [comment]
just done some further testing and see that position number doesn't show effect for sorting. Last sub-page created will be placed on top, then gradually by page creation date/time sorted downward in NavMenu. OK, I can deal with this, not really what I had expected tho.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
