### ISSUE TITLE
WebP Thumbnails do not show in uploader

### ISSUE THREAD

**Issue by kolim4801** [bludit/bludit#1168]
### Describe your problem
I use webp format for my images - and when I upload a webp file the thumbnail in the uploader shows black. This is a minor problem since once inserted the image shows perfectly fine.

### Steps to reproduce the problem
You can follow up my support request here: https://forum.bludit.org/viewtopic.php?f=6&t=1728

### Bludit version
3.12.0

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
