### ISSUE TITLE
File name on disk for content

### ISSUE THREAD

**Issue by dgleba** [bludit/bludit#1169]
### Describe your problem
The name of the file for content is index.txt.
Is there a way to have it named with the title of the post, the way the folder is named?

### Bludit version
```
docker latest - 2020-03-30, but in about it says..

Bludit Edition | Standard - Upgrade to Bludit PRO
Bludit Version | 3.8.1
Bludit Codename | APA
Bludit Build Number | 20190228
```

### PHP version
docker official latest

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
