### ISSUE TITLE
Delete a folder image in a article

### ISSUE THREAD

**Issue by kosi777** [bludit/bludit#1170]
After deleting an article, the image folder is not deleted!

What you need to do to delete the folder?

I'm using the latest version of bludit.

### PHP version
Php 7.3

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
