### ISSUE TITLE
Use a database

### ISSUE THREAD

**Issue by Kazem-ma79** [bludit/bludit#1187]
How to use a database and store content on DB ?
I know this is a flat-file cms and doesn't need any database but I'm needing to change it to a DB based cms and store any data like content and settings on db.
Is it possible ? if yes how ?

**Comment by SamBrishes** [comment]
Hellow,

Even a Flat-File system has a database, but in this case there is no complex system behind it, just a simple JSON file and a respective PHP class.

The JSON database magic happens within the [bl-kernel/abstract/dbjson.class.php](https://github.com/bludit/bludit/blob/master/bl-kernel/abstract/dbjson.class.php) file. Use this as your parent class and store your database content within the public class variable `$db`. To store / update the JSON file use the `save()` method. (If you need a more complex example, check out the [system/reactions.php file](https://github.com/pytesNET/reactions/blob/master/system/reactions.php)  of my reactions plugin which uses dbJSON as parent).

BTW.: If you're developing a Plugin, the parent `Plugin` class itself does already have a database JSON file for your Plugin. So in this case use the `init()` method or your main class and store your data within the `$dbFields` variable as shown on the core [search plugin](https://github.com/bludit/bludit/blob/master/bl-plugins/search/plugin.php), for example.

Sincerely,
Sam.

**Comment by Kazem-ma79** [comment]
Yes I saw them and know it, but I'm looking for MySQL or a way to extract data from files.

**Comment by SamBrishes** [comment]
If you really need a MySQL database you need to create your own class, because Bludit doesn't have such a tool. 

You say you want to store your content and settings on a database, but why is a JSON database file not enough? 

> or a way to extract data from files.
Which data do you want to extract from which kind of files?

**Comment by Kazem-ma79** [comment]
I'm using Bludit for a business website and my most important points are performance and security, so we can't store our data on a file.

**Comment by SamBrishes** [comment]
Of course, you can store your data within a file. The content of a MySQL Database is also stored in a file (of course not a plain text file, but still visible with a little effort), it is just **outside** the webspace `www` directory. So if you own a server, not a webspace, you would be able to change the `PATH_DATABASES` constant path and store the JSON database files outside the root directory of your website.

However, since Bludit is based on a JSON Flat-File system you aren't able to switch to MySQL without adapting the whole system or at least the main database classes `dbjson.class.php` and `dblist.class.php`. Nevertheless, that would be a major intervention, which would nullify the system's ability to update.

**Comment by dignajar** [comment]
Hi,
yes, you need to write your own classes for integrating with MySQL.

Regarding to security, please read the documentation section "Security", also let me know what webserver you use, Bludit by default creates a .htaccess for Apache with some security to sensitives files.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
