### ISSUE TITLE
[REQUEST] Customizable dashboard views

### ISSUE THREAD

**Issue by Kazem-ma79** [bludit/bludit#1191]
Please make dashboard views more customizable to make creating admin themes easier.
I'm making some themes but can't use default views, so I need to make another views or don't use any views on my theme.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
