### ISSUE TITLE
Store XSS

### ISSUE THREAD

**Issue by 3as0n** [bludit/bludit#1212]
### Describe your problem
https://github.com/bludit/bludit/blob/master/bl-kernel/ajax/logo-upload.php

Logo upload only determines the suffix, but not the content, which causes XSS
and the user can inject any javascript and html code in the page

payload
![image](https://user-images.githubusercontent.com/8120951/85107565-c28ea200-b240-11ea-9967-e68dc6b38462.png)

![image](https://user-images.githubusercontent.com/8120951/85107027-d4237a00-b23f-11ea-904b-143e35b6e1e8.png)
![image](https://user-images.githubusercontent.com/8120951/85107079-ea313a80-b23f-11ea-98e1-3f1d683356d5.png)

**Comment by galaktipus** [comment]
Any knows fix for issue yet? Seems like it was assigned to CVE-2020-15006

**Comment by bj60907811** [comment]
Yes, this is the cve number. I think we can either delete the svg format or add a check mechanism. But it affects performance.

---Original---

**Comment by dignajar** [comment]
I will check, is not a problem for Bludit because the users are trusted by the Administrator, I mean Bludit doesn't have user registration.

Feel free to provide a fix for it.

Regards

**Comment by bj60907811** [comment]
If people enter the background, they can use this vulnerability to spread or fish malicious JS. If someone's domain name is trusted









------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Diego Najar"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月25日(星期四) 晚上8:38
收件人:&nbsp;"bludit/bludit"<bludit@noreply.github.com&gt;;
抄送:&nbsp;"仁豪装饰"<171583065@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bludit/bludit] Store XSS (#1212)





 
I will check, is not a problem for Bludit because the users are trusted by the Administrator, I mean Bludit doesn't have user registration.
 
Feel free to provide a fix for it.
 
Regards

**Comment by SamBrishes** [comment]
Vector Images are really important (especially for responsive design), but many Content Management Systems avoid them because detecting and filtering XSS is a horrible job.

However, losing SVG Support in Bludit shouldn't be the way to go. So how about the following Validation function (can be part of the Valid helper class). It's may not perfect now, but it works on the most common XSS attacks and I also checked the used Regular Expression against [MDN's SVG Attribute's list](https://developer.mozilla.org/de/docs/Web/SVG/Attribute) to avoid false positives.

```php
<?php

class Valid
{
    static public function svg($content, $requireDoctype = false) {
        if($requireDoctype && strpos($content, "<!DOCTYPE") !== 0) {
            return false;
        }

        // Validate XML Format
        try {
            $xml = @new SimpleXMLElement($content);
        } catch(Exception $e) {
            $xml = false;
        }
        if(!$xml) {
            return false;
        }

        // Check Basic XSS
        if(!!preg_match("/(<(\/)?script|on[a-z]+=|(java)?script:)/i", $content)) {
            return false;
        }
        return true;
    }
}

```

~ Sam.

**Comment by SamBrishes** [comment]
We can also add the following regular expression to avoid URLs except the w3.org standards, which may leads to false positives if someone adds a URL as comment. This is also not fully tested yet.

```
(http.)?(:)?\/\/(www\.)(?!w3\.org)
```

**Comment by working-name** [comment]
@SamBrishes That regex is a good start but it gets complicated fast: https://owasp.org/www-community/xss-filter-evasion-cheatsheet

Especially when you can have whitespace in the word 'javascript:'. Let me know if you're serious about using regex for this, I'd be happy to make one that catches the known methods people use to bypass xss checks.

**Comment by bj60907811** [comment]
It's a good idea.



---Original---

**Comment by SamBrishes** [comment]
> Especially when you can have whitespace in the word 'javascript:'. Let me know if you're serious about using regex for this, I'd be happy to make one that catches the known methods people use to bypass xss checks.

Feel free to bypass the regex, but keep in mind, that you still need to be a valid XML file according to `SimpleXMLElement`.

Of course, we can also use an (adapted) version of the Ulf Harnhammar's [Kses Library](https://github.com/pytesNET/php-helpers/blob/master/PIT/Kses/Kses.php) and check each single tag and attribute available in a SVG image only, but I don't think that this is really necessary. 

Anyway, Bludit should also just allow admins to upload SVGs to restrict the responsibility and I guess it is also important to check the MIME type of images too, next to the file extension. (For example as I'm using it on my [media](https://github.com/pytesNET/media/blob/master/system/manager.php#L183) plugin).

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
