### ISSUE TITLE
Adding messages to the plugin Search

### ISSUE THREAD

**Issue by clickwork-git** [bludit/bludit#1213]
Adding messages to the plugin Search for cases
* the search contains less than 5 characters,
* nothing is found.

**Comment by SamBrishes** [comment]
A few additional options would also be cool, something like

- Search Case-Insensitive (which stores everything lowercase)
- Adapt the minimum characters for a search
- Adapt the Cache Size of the Page Content (currently static to 800 * 5 characters)
- Change the Search Algorithm of Fuzz

**Comment by dignajar** [comment]
@SamBrishes do you have in mind a better search algorithm?

**Comment by SamBrishes** [comment]
@dignajar No, I meant allowing to switch between Levenshtein and Jaro-Winkler, since Fuzz supports both search algorithms. As far as I know Jaro-Winkler is more optimized for shorter strings, while Levenshtein is more accurate on longer ones. But, of course, Jaro-Winkler should be faster.

I guess Fuzz should also switch to the core `levenshtein()` php function to increase the performance instead of using a custom one, but I didn't test it yet.

I'm currently playing around with these and running a few benchmarks on both.

**Comment by dignajar** [comment]
I just add to the settings of the plugin search the ability to choose the number of chars

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
