### ISSUE TITLE
Can't edit free text settings thru admin panel if ModSecurity is set Active

### ISSUE THREAD

**Issue by sjuhani** [bludit/bludit#1216]
### Describe your problem
If ModSecurity is in Active state, the new Bludit, at least version 3.12.0, causes an irritating false positive problem with ModSecurity when trying to edit the free text kind of settings in Bludit Admin Panel. The problem is detected by ModSecurity the following way:    _[id=340162] Atomicorp.com WAF Rules: Remote File Injection Attack detected (Unauthorized URL detected as argument)_
 
The problem though does not occur in at least some older Bludit versions, like 2.3.4 (alongside with exactly same ModSecurity config and rules, but PHP 5.6.40).
 
### Steps to reproduce the problem
ModSecurity set to Active operation state, default rules. Then, try to edit Bludit settings which are free text, using its admin panel. **For example,** General settings including website title, slogan, description, and footer text (of which default value is "Copyright © 2020"), as well as tag and category URLs from the Advanced settings.

### Bludit version
3.12.0

### PHP version
7.4.7

**Comment by SamBrishes** [comment]
Hellow,

are you using Bludit on a local server or by using the direct IP address of your Server instead of a domain? I created a similar setup and encountered this issue only using the IP instead of a (virtual) domain.

**Comment by sjuhani** [comment]
I am using this paid webhosting plan: https://www.freehostia.com/hosting/watercircle-plan – so, I think that the problem may not be limited to direct IP thing. I have domain names for both the Bludit version 3.12.0 test setup where this problem occurs and the old one and both of the websites' frontends are also publicly, globally viewable by any decent web browser just using the domain name. Both of these setups are running under the very same hosting plan account, and both of them have htaccess set up to force HTTPS protocol and ensure that its URLs are without the beginning "www".

**Comment by SamBrishes** [comment]
This seems to be a really hard problem. 

After a small research I figured out, that the rule [WAF 340162](https://wiki.atomicorp.com/wiki/index.php/WAF_340162) (which causes this issue) is a commercial rule of [modsecurity](https://modsecurity.org/rules.html) and therefore I couldn't "trap" to the same error (since I'm just using the free version, of course :D). 

However, I've no idea how this issue can be fixed, but maybe @dignajar finds a solution for this. The only thing I could find was the following entry in the documentation of the [IndieAuth](https://indieweb.org/Wordpress_IndieAuth_Plugin) WordPress plugin at point **ModSecurity Firewall blocking requests**:

>
> ### ModSecurity Firewall blocking requests
> On servers using the ModSecurity Web Application Firewall, with Atomicorp.com WAF Rules requests may be blocked because of WAF 340162. This rule blocks requests that use external URLs in the URL, to protect against Remote File Injection. 
>
>  **Temporary solutions:**
> - ask the hosting in charge of the firewall to disable this rule, 
> - or disable it yourself if you have access to server configuration files (this may also work in .htaccess files):
>
> ```
> <IfModule mod_security2.c>
> SecRuleRemoveById 340162
> </IfModule>
> ```
> **Real solution:**
> From the WAF Rule description:
> > It is not recommended that you disable this rule if you have a false positive. If you believe this is a false positive, please report this to our security team to determine if this is a legitimate case, or if its clever attack on your system. Instructions to report false positives are detailed on the Reporting False Positives wiki page. If it is a false positive, we will fix the issue in the rules and get a release out to you promptly.
>
> This may only be available to Atomicorp customers? 

Sorry.

**Comment by sjuhani** [comment]
I tried out the quite dirty temporary solution (.htaccess ---> SecRuleRemoveById 340162), but all these kind of exclusions seem to be turned off on the webhost. And, there is no access to the server config files because they are same for all customers, as well as the ModSecurity firewall rules, meaning that the hosting provider is not going to make any special alterations to them either. 
  
Currently, the only possibility for me and many others to run up-to-date version of Bludit without these problems is to keep ModSecurity **only** at the operative mode **Detect**, at least when updating the free text kind of settings. Basically, though, this is **comparatively far from optimal what comes to online security nowadays.**

As a conclusion, **this problem should be able to be fixed in Bludit itself,** as the older versions do not have this issue, which seems like there must have been another way to pass those free text setting values from the admin panel user interface to the Bludit's flat-file database.

**Comment by SamBrishes** [comment]
Hard Road through WAF rules, but I guess I found a solution for this issue. Can you please download the ZIP below and replace the containing `bl-kernel/url.class.php` and `bl-kernel/admin/views/settings.php` files with your Bludit installation:

[bl-kernel.zip](https://github.com/bludit/bludit/files/4840087/bl-kernel.zip)

The files just adds a `.php` ending on the respective `admin/settings` form. This way the post request should be passed using one of the default `MatchLocation` filters of modSecurity.

Thanks.

**Comment by sjuhani** [comment]
Yes, that fixed the problem completely. 👍 😊 So, seems to be the time to make a pull request, too.

**Comment by SamBrishes** [comment]
Perfect :D Pull Request has been submitted, a bit differently but with the same result.

**Comment by dignajar** [comment]
Hi guys,
I really don't like the idea to add code to fix problems from other systems, this is a false positive detected from Modsecurity, to do it in a correct way is to remove this rule or whitelist your domain in Modsecurity.

The previous version of Bludit don't have the URL /admin/settings, so that why is not catch by Modsecurity.

**Comment by sjuhani** [comment]
Hello there, dignajar 
 
Well, at the level of thought the root of the problem in this case may lie there in the ModSecurity's threat prevention rules. Though, it is darn complicated to get those things sorted out in that firewall system because their policies require vast amounts of various technical information to report a false positive (_https://support.atomicorp.com/hc/en-us/articles/360000584688-Reporting-False-Positives-when-not-running-ASL_), and most of that information is not available for webhosting customers like me. 
 
As a reminder, let's also not forget something that was stated earlier in this issue thread. The idea of domain whitelisting or disabling the particular rule is actually **not** a bright one – for more than just one reason. Speaking of 'em, let's pay attention especially to the fact that doing so will open holes for attackers to intrude. It should also be recalled that typical web hosting customers (like me) do not even have any possibility to set individual rule exceptions because of the fact that all web hosting customers on the platform share the global rule set.
 
Anyways, I naturally will try to contact my webhosting provider and refer to this issue thread.

**Comment by dignajar** [comment]
What we can do in new version is to avoid the URL `/admin/settings` and setup another URL.
Ideas for a new URL ?

**Comment by SamBrishes** [comment]
Hellow,

I couldn't stop thinking about this issue, also because Bludit v2.x works but Bludit v3.x doesn't. After dozens of tests and workarounds I discovered the reason why v.3.x doesn't pass the rule any more:

Mod Security doesn't like the social media URL fields!

The Site URL form field (as I assumed before) is completely irrelevant and @dignajar it also doesn't help to change the URL, since mod security always requires an ending (such as `.php` or `.cgi`) if you want to skip the respective rule filter.  So maybe I found a solution, which doesn't change the core routing system and may also improve the settings page too. I'll post it here, after I tested it completely.

~ Sam.

**Comment by SamBrishes** [comment]
A few tests later, I found a working solution.

You could add `[url]` on the name of the respective network fields... So instead of ...

```html
<div class="col-sm-10">
    <input class="form-control " id="jstwitter" name="twitter" value="" placeholder="" type="text">
    <small class="form-text text-muted"></small>
</div>
```

... you could change it to the following and filter the URL part of the form field on the backend

```html
<div class="col-sm-10">
    <input class="form-control " id="jstwitter" name="twitter[url]" value="" placeholder="" type="text">
    <small class="form-text text-muted"></small>
</div>
```

In this case you could theoretically also re-design the social network part. I mean instead of offering a bunch of networks, which may gets obsolete like Google+, you could also offer a free text field. This way the user can add all the networks he wants to, without being restricted to the existing ones. Something like

![socialnetworks](https://user-images.githubusercontent.com/31392477/86518412-42685f00-be32-11ea-863e-60f99d5ee75b.JPG)

But that's just an idea.

~ Sam.

**Comment by sjuhani** [comment]
I warmly support the ideas such as presented by SamBrishes which improve well-advised flexibility and longevity.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
