### ISSUE TITLE
RFE: make symlinks optional

### ISSUE THREAD

**Issue by LiohMoeller** [bludit/bludit#1236]
There are a few places in bludit where symlinks are in use. Some of them are necessary, some not, like the named links in bl-content/uploads/pages/ which seem to be completely optional at the moment. This is not the case for svg thumbnail symlinks, which are required.

![links](https://user-images.githubusercontent.com/1267594/87645938-74d95c80-c74e-11ea-8898-4c6c06b7ae6b.png)

In general symlinks are fine when created with PHP but some webhosters only provide FTP access and using FTP it is not possible to backup/restore those links as it is not part of the protocol specifications.

I would like to ask to either remove/replace the symlink feature or make it optional (off by default), which could be easy for the named links in bl-content/uploads/pages/ but would lead to duplicate content for svgs (which is not a big issue as the overhead is probably small). This would allow consistent backup / restore on hosts where only FTP access is available.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
