### ISSUE TITLE
[Request] Add More Custom Fields Types

### ISSUE THREAD

**Issue by OffLine101** [bludit/bludit#1237]
### Hello
**we need to Add More Custom Fields Type because we need it**
those are some exp of what new type will be ;
https://www.advancedcustomfields.com/resources/taxonomy
https://www.advancedcustomfields.com/resources/repeater
https://www.advancedcustomfields.com/resources/oembed
https://www.advancedcustomfields.com/resources/wysiwyg-editor
https://www.advancedcustomfields.com/resources/select
https://www.advancedcustomfields.com/resources/true-false
https://www.advancedcustomfields.com/resources/checkbox
https://www.advancedcustomfields.com/resources/textarea

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
