### ISSUE TITLE
Addition of "Delete" to the dashboard search

### ISSUE THREAD

**Issue by clickwork-git** [bludit/bludit#1259]
At the moment content can be searched, viewed and edited by using the search in the dashboard. An additional link to delete content would be useful.

![grafik](https://user-images.githubusercontent.com/14312561/90911101-bfe33100-e3d8-11ea-96f9-115349a673a9.png)

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
