### ISSUE TITLE
remote-content plugin - add image support

### ISSUE THREAD

**Issue by marcusyoung** [bludit/bludit#1260]
### Describe your problem

A method to add image link to index.md and save the images in the same folder and then have those images automatically imported into the site and linked?

### Bludit version
3.13.1

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
