### ISSUE TITLE
image/avif does not work

### ISSUE THREAD

**Issue by clickwork-git** [bludit/bludit#1264]
### Describe your problem
The MIME type _image/avif_ does not work.

### Steps to reproduce the problem
Adding _image/avif_ to the files variables.php and media.php of the admin theme.

### Bludit version
3.13.1

### PHP version
7.4.9

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
