### ISSUE TITLE
Draft does not work

### ISSUE THREAD

**Issue by clickwork-git** [bludit/bludit#1268]
* If a content is set to "Draft" and then saved the content is set to "Publish".
* If a content is set to "Draft" and closed the content is set to "Publish" when it is reopened.

This happens if the content is set to "Static" (v3.13.0).

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
