### ISSUE TITLE
TinyMCE disappears with many custom fields

### ISSUE THREAD

**Issue by puschmie** [bludit/bludit#1281]
### Describe your problem
When adding a bunch of custom fields to the content creation page, the TinyMCE editor doesn't have enough space and can't be used. The page doesn't automatically extend. See the screenshot for an idea.
### Steps to reproduce the problem
Just add a bunch of custom fields, until the page is full.

### Bludit version
3.13.1

### PHP version
7.2.24
![image](https://user-images.githubusercontent.com/71654862/97590462-ee940e00-19fe-11eb-832f-01b69fa13b4e.png)

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
