### ISSUE TITLE
The "Custom fields parser" -plugin messes with images? (all images disappears)

### ISSUE THREAD

**Issue by 2f2a** [bludit/bludit#1285]
### Describe your problem

If the plugin is enabled, images in the post's disappears, and the tag ![]() visible, on front-page.

### Steps to reproduce the problem

After followed the last example in the document, the youtube -link embedded thingy.

Why this plugin ("Custom fields parser") wasn't enabled by default, I dono, -its in main docs. Here:
https://docs.bludit.com/en/content/custom-fields
(wana recall, that following this docs steps on "here > there > here > .." was sortof confusing)

Also if enabled (with youtube thingy), it breaks the "Perfect Bludit" -theme. only showing the last youtube post.

### Bludit version
Complete here. 3.13.1

### PHP version
PHP Version 7.4.11
I just testing Bludit local (as /~username). 

### PHP logs
No errors.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
