### ISSUE TITLE
afterPageCreate hook is not called when scheduled page gets published

### ISSUE THREAD

**Issue by johanez** [bludit/bludit#1307]
### Describe your problem
`afterPageCreate` hook is not working when scheduled page gets published. The [documentation](https://docs.bludit.com/en/plugins/pages-after-creation) mentions this should happen, but it does not. The responsible code in `69.pages.php` row 39-51 does not seem to be called, the log never shows  'content-published-from-scheduler'.

### Steps to reproduce the problem
- Create a page, schedule it
- Wait for scheduler to publish
- check log for 'content-published-from-scheduler' and/or use a plugin that should act on this hook. neither happens. 

### Bludit version
3.13.1

### PHP version
7.4.3

**Comment by dignajar** [comment]
Fixed for Bludit v4

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
