### ISSUE TITLE
[Suggestion] Recycle bin for deleted content

### ISSUE THREAD

**Issue by PhotoLinux** [bludit/bludit#1309]
Today I had the problem that I accidentally deleted a blog article. Also under "Content > Automatically saved" the article was no longer to be found.

It would be good if Bludit had a "recycle bin" for such deleted content.
Any deleted blog article or other content should then be able to be found in this "recycle bin" to be restored or permanently deleted.
It would be great if this feature would be implemented in future versions.

What do you think about that? Is that possible?

**Comment by dignajar** [comment]
Hi,
yes it's possible to implement a recycle bin;

For Bludit PRO we provide TimeMachineX so you can restore to a previous point.

**Comment by PhotoLinux** [comment]
> yes it's possible to implement a recycle bin

That would be awesome if you could implement that.
Thanks in advance!

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
