### ISSUE TITLE
[request] Discord Social

### ISSUE THREAD

**Issue by Loopios7** [bludit/bludit#1311]
Seems like something useful for a lot of communities.

**Comment by dignajar** [comment]
I added for Bludit v4.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
