### ISSUE TITLE
[REQUEST] Manage of tags in Admin Dashboard

### ISSUE THREAD

**Issue by ghost** [bludit/bludit#1315]
Is there a way we can manage tags from the admin backend. If not this feature would be very useful.
I have just started using Bludit and after trying multiple Flat File CMS - I gotta say this is the best one which fits all requirements. It’s super easy to setup and start running.

Though I am not a PHP developer, but I would love to contribute and provide feedback. I am from India and my company is into helping small businesses setup their online presence. Bludit is perfect for most of the requirements and there are some features that will just make it the best choice over static websites. Here are some features I would like to suggest -

- Plugin for Testimonials
- Option to manage tags from backend (similar to categories). Deleting unwanted tags will be a boon.
- Option to select tags in content pages. Currently we have to remember all the tags and as there are no way to check / manage the existing tags, a lot of duplicate tags are being created.
- Also how does Draft work - Is there a way where I can convert published post back to drat

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
