### ISSUE TITLE
Simple Responsive Tables plugin

### ISSUE THREAD

**Issue by stani63** [bludit/bludit#1316]
For GRAV there is a simple and well-functioning plug-in _[Simple Responsive Tables](https://github.com/bgartenmann/grav-plugin-simple-responsive-tables)_.

Such an plugin would be very suitable for Bludit.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
