### ISSUE TITLE
2FA Support to protect Admin portal

### ISSUE THREAD

**Issue by jdtate101** [bludit/bludit#1322]
### Describe your problem
Feature request to have a TOTP authentication module to protect the admin pages, so help protect from unauthorised access. Integration with Google Authenticator and like services would be great.

### Bludit version
3.13.1

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
