### ISSUE TITLE
search Plug-inDoesn’t seem to support Chinese search

### ISSUE THREAD

**Issue by xiamuguizhi** [bludit/bludit#1372]
![](https://vkceyugu.cdn.bspapp.com/VKCEYUGU-2fa930c8-feec-4942-ac88-ba3781377bb0/0f688c87-b962-4f8d-b888-c15ae31f0c4d.png)

The same article I use Chinese search can’t prompt that it does not exist. If I search for the article’s English vocabulary, it displays normally

**Comment by akacruise0621** [comment]
I have the same problem，Bludit 4.0

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
