### ISSUE TITLE
h1 html problem

### ISSUE THREAD

**Issue by monte134** [bludit/bludit#1455]
I try to use Bludit CMS with Blog X theme.
But in the code (view-source in chrome) I only see the h2 html tag for the post titles. 
Tag h1 is not available by default settings. This is not good for SEO. 
I have no idea how to fix it correctly. Is it possible to fix this (h2 -> h1) or add a special option???

Bludit ver. 3.14.1

**Comment by csaszarpeter** [comment]
Yes, H1 is important in SEO, but each page should only have one H1.
On the main page of Blog X theme is a list of posts with H2 titles. It is normal that these are not listed with H1 titles, because then there would be e.g. 3-5-15 pieces of H1 on the main page. (If you click on a post, on its subpage the title will already be in H1.)
To have H1 text on the main page:
a. use a plugin
b. insert your own snippet into the file bl-themes/blogx/php/home.php (e.g. line 6).
