### ISSUE TITLE
[Plugin Visits Stats] Incorrectly counts visits.

### ISSUE THREAD

**Issue by Elixcz** [bludit/bludit#1466]
The visits Stats plugin incorrectly counts visits. If there are meta tags in the theme header (e.g. favicon, apple-touch-icon, etc.) the plugin counts each GET request as a one visit.

**Bludit 4**
Visits Stats
(the same in the simple-stats plugin in Bludit 3.14.1)
Firefox 105

**Comment by dignajar** [comment]
looks like more of an issue with the webserver, because if the request goes to a favicon, the webserver should catch that route and not execute Bludit.

The plugin count when the Bludit page is rendered also at the end of the render.
https://github.com/bludit/bludit/blob/main/bl-plugins/visits-stats/plugin.php#L116
