### ISSUE TITLE
More language mutations allowed

### ISSUE THREAD

**Issue by Deight8** [bludit/bludit#1479]
I'm reading the documentation and either I didn't understand it or it still doesn't work.

Is it possible to half-cast multiple site language localizations so that I can navigate visitors through pages in different languages?

/home/en/
/home/fr/
...

Thank you

**Comment by G3N-es** [comment]
There are several ways:

1. The best option: Install several Bludit, one for each language. It gives you a good SEO because it allows you to translate urls. It is cumbersome to update, the only drawback.
2. Create child pages and make them the translations. This would look like this in English Spanish:
mysite.com/who_we_are/es
Where "/es" would be the slug of a child page "Quienes Somos".

It is easier to manage because you only have one Bludit installed. The only problem is SEO. All translated urls will have the same slug /es, on the right side of the parent page.

---

No one has yet developed a plugin to enable translations. Translation plugin is not easy to develop. There are many possible approaches and all have pros and cons. There have to be ways to communicate the pages with each other and make decisions if one is updated and the others are not.

In fact in wordpress where there are thousands of plugin developments, I have yet to find one that satisfies me 100%. Either they are difficult to manage, or they don't have a good SEO.
