### ISSUE TITLE
Integration of plugin settings

### ISSUE THREAD

**Issue by nickbe** [bludit/bludit#215]
It seems that the setting coming from plugins are still drestricted to being kept in the plugin list.
Is it not possible to integrate settings into the standard setting panel, or maybe add additional setting panels to the dropdown menu?

**Comment by dignajar** [comment]
Hi, sorry I don't understand.
Each plugin has a settings (if the plugin need it).

**Comment by acrox999** [comment]
I think what you're trying to achieve is just going to be the same thing. If you meant adding link to the enabled plugins settings, that's going to make the menu more cluttered.

But I guess we can make it so that the Plugins page show Enabled first before Disabled plugins, to navigate them a lot easier.

**Comment by nickbe** [comment]
Ok then what about this: A simple switch on the plugin page: Switching between "Install/Edit Plugins" and "Use plugins". When the switch is on default "Use Plugins" you only show the plugins in the list with actions that can be done. Other plugins with only settings or no settings/actions at all are only shown in the "Install/Edit Plugin" mode.
This way the plugin panel could be shown as smaller "panels" instead of lines, making it compact and more easy to use.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
