### ISSUE TITLE
(Too) large profile image after upload

### ISSUE THREAD

**Issue by MaxMalRichtig** [bludit/bludit#261]
I've noticed, that after uploading a profile picture, it gets converted to a 400x400px png-image. These files get quite large (200-400kB) which leads to an extended access time, when switching to the blog after changing the pic. Is there a specific reason for not using a more compressed JPG in the uploader.php and other files that use the profile-pic? In my opinion a 20-50kB pic would be enough.

And: uploading an profile-image that is smaller than 400x400px leads to black boarders around the picture (uploader.php forces 400x400px) instead of just a smaller profile picture. 

Any thoughts on that?

**Comment by clickwork-git** [comment]
Diego will have a look at it when he will be back of his holidays.

What is the size (kb) of the original picture?

**Comment by Max-malRichtig** [comment]
Nice to hear that!

I've tried various images: uncompressed .PNG with ~750kb down to compressed .jpg with ~20kb. All of them had at least 400x400px due to the black borders the processed images get after upload.

All of them are 200-400kb big after processing.

I already played around with the code and managed to get two working versions: one with a smaller, uncompressed PNG (e.g. 200x200px, 50-100kb) after upload, the other with a compressed jpg after upload (various px, various KB - easily down to 20 KB)

I'm not sure what would be the best thing to do. Do we need high quality profile pics? Do we always need PNG? Would it be cool to have a compressed jpg when uploading a jpg and an uncompressed PNG when uploading a PNG?

**Comment by clickwork-git** [comment]
Similar problem with images and thumbnails. Thumbnails are larger than images.

**Comment by dignajar** [comment]
Hi,
the png format is because some users need to upload profile picture with transparent background.

There are two constants, in /bl-kernel/boot/init.php

THUMBNAILS_WIDTH
THUMBNAILS_HEIGHT

You can change the size of the thumbnails.

PD: I will add two constants more, for the size of the profile picture.
