### ISSUE TITLE
Tags and draft

### ISSUE THREAD

**Issue by clickwork-git** [bludit/bludit#274]
New added tags are not saved when saving a post as draft or setiing from published to draft.

**Comment by xm74** [comment]
Confirm

**Comment by janxb** [comment]
@dignajar.
Right now, [dbTags is storing only published posts](https://github.com/dignajar/bludit/blob/fae098ee6f56b535fbc3c7db64df1a16db66461a/bl-kernel/functions.php#L11-L18). 
So as i see this, there are two possible ways to solve this:

1. The dbTags could store every post (unpublished too) and we filter after creating every post object
2. The dbTags stores every post and we add an additional field (like in dbPosts), so we can filter directly in this class.

I would go for number 2, because the behavior would be similar to dbPosts. But i don't want to refactor without asking for your opinion.. ;)

**Comment by janxb** [comment]
Yes it has, see here ;)
https://github.com/dignajar/bludit/issues/263

**Comment by alexandreteles** [comment]
> @dignajar said:
> The dbTags stores every post and we add an additional field (like in dbPosts), so we can filter directly in this class.

I think this is a more elegant solution to solve this problem. This issue should be a priority because, in some way, it broke Bludit's main functionality and It's really annoying :D

**Comment by dignajar** [comment]
Tags are improved on Bludit v2.0.
