### ISSUE TITLE
Bug in "log" (and "future-imprefect") theme layout

### ISSUE THREAD

**Issue by xm74** [bludit/bludit#275]
Corrupted left panel in main and posts but ok in pages.
See screenshots.
http://imgur.com/a/nPuvM

**Comment by dignajar** [comment]
Hi,
I think is because the title, I will check with large titles..

thanks

**Comment by xm74** [comment]
Thanks a lot!

**Comment by anaggh** [comment]
This bug also exists on Blogme theme.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
