### ISSUE TITLE
Theme Log: Print problem

### ISSUE THREAD

**Issue by clickwork-git** [bludit/bludit#351]
There are problems with formatting to print the pages.

**Comment by dignajar** [comment]
I think this issues was solved? can I close it ? I'm cleaning this issues

**Comment by clickwork-git** [comment]
I have not yet fixed it.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
