### ISSUE TITLE
Add multi-language support

### ISSUE THREAD

**Issue by DonHege** [bludit/bludit#393]
Hi everyone, 

I think it would be nice to have two different language versions at the same on the same system. So whenever I write a new article I'd like to be able to add a version in a different language (e.g. one in German, one in French) and the user would be able to toggle between languages.

Maybe this is worth implementing in the mid-term.

**Comment by clickwork-git** [comment]
Language management is not an easy task. At the moment I recommend two installations, for example mydomain.de and mydomain.de/fr.

**Comment by DonHege** [comment]
That's right, but it might fit on some sort of mid-term roadmap.

**Comment by cyberviews** [comment]
It would still be a great feature, not to have to log in in two admin panels. And it would enhance the user experience, if a user klicks on a lik to show an article in another language without being redirected to the index page of the other installation.

Maybe a paid plugin would be an option?

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
