### ISSUE TITLE
Hyphens in friendly URL

### ISSUE THREAD

**Issue by clickwork-git** [bludit/bludit#440]
When modifying a friendly URL is it not possible to use hyphens (but is is possible to write the friendly URL and then insert hyphens).

**Comment by dignajar** [comment]
The hyphens are allow only 1 beteween words in Bludit v3.x

Allow:
`example-example`

Not allow:
`--example-example`
`example--example`
`example-example--`

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
