### ISSUE TITLE
Some options not available on narrow screens with Bludit 2.0

### ISSUE THREAD

**Issue by JonathanHolvey** [bludit/bludit#539]
If you edit a page using a small screened device like a phone or tablet, the controls for adding images and tags, and other page/post options aren't visible. I believe with Bludit 1.6.2 these options were available below the editor input field.

~~Also, access to the sites settings are missing from the pull out menu on the left of the admin area, and the bottom of the edit user page is cut off.~~ This, it turns out was caused by some CSS being cached from the old version of Bludit.

I'm using Chrome on Android.

**Comment by ADTC** [comment]
I made a PR. It should fix this.

Just so you know, it wasn't fixed then broken. It was **never fixed** at all. Issue #401 was just a proposal to fix it.

**Comment by dignajar** [comment]
Merged. I would like to do something like this and remove the right sidebar, because is to much space.

Left sidebar | Form | Right sidebar

I want to do this

Left sidebar | Form

<img width="787" alt="screen shot 2017-10-25 at 19 12 24" src="https://user-images.githubusercontent.com/507352/32012587-a34ef6fc-b9b8-11e7-84d8-2e0034aa247e.png">

**Comment by ADTC** [comment]
Thanks. Yes, that would be better. In fact, I found the sidebar taking up too much space on the desktop that I hacked its width to be narrower (user-adjustable width would have been awesome though).

How would it function on mobile view though?

**Comment by dignajar** [comment]
I'm looking for some framework, and I found this one.

Here are the tabs:
https://bulma.io/documentation/components/tabs/
