### ISSUE TITLE
[Plugin] Backup improves

### ISSUE THREAD

**Issue by clickwork-git** [bludit/bludit#605]
1. Notification if a backup is successfully restored.
2. Possibility to delete backups.
3. Upload zip file with a backup and apply this backup.

**Comment by dignajar** [comment]
2. Possibility to delete backups is implemented.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
