### ISSUE TITLE
[CORE] Preview page button / link

### ISSUE THREAD

**Issue by Bayerberg** [bludit/bludit#648]
New content / edit page 

It would be great to have a preview page button, something along the lines of 
`<a class="uk-button" href="'.$page->permalink().'" target="_blank">'.$L->g('Preview page').'</a>`
You could place it next to save buttons or in the sidebar

In addition edit-content.php could have an active link on the page title just under 
`<h2 class="title"><i class="uk-icon-file-text-o"></i> Edit content</h2>`
something like 
`<h3 class="page-title"><a href="'.$page->permalink().'" target="_blank">'.$page->title().'</a></h3>`

**Comment by dignajar** [comment]
For this is necessary to save the page and then do the preview, the thing is necessary add some status to this page `published` or `draft`.

Maybe is possible to store as a `draft`, and then is possible to make the preview. I need to check it.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
