### ISSUE TITLE
[CORE] Site logo

### ISSUE THREAD

**Issue by dignajar** [bludit/bludit#718]
- Select a picture as Site logo

**Comment by dignajar** [comment]
Implemented in Bludit v3.6. Thanks.

**Comment by Joduai** [comment]
Shouldn't site logo be accessible via a global(?) variable like "$site->logotype()"?

Since uploaded logo image is renamed in the manner sitename.extension I made a simple approach to search through all files in bl-content/uploads/ 
`$sitelogo = glob(PATH_UPLOADS.$site->title().'.{png,jpg,jpeg,gif}', GLOB_BRACE);`

and display the first logo image occurence, if there are other img type available:

```
if (count($sitelogo) > 0) 
{
echo '<img src="'.HTML_PATH_UPLOADS.basename($sitelogo[0]).'" alt="logo" class="logo">';
}
```
This could be more foolproof as I'm not sure how special chars are handled in site name.

btw. upload directory could be moved to root directory. Especially if bludit gets one day an internal media manager (not an additional plugin content editor plugin)

**Comment by dignajar** [comment]
Hi,
there is a method, `$site->logo()`.

https://github.com/bludit/bludit/blob/master/bl-kernel/site.class.php#L275

**Comment by Joduai** [comment]
Ohhh, thanks for mentioning.
I should have had a look also at class files instead of only checking variables inside kernel/boot/  dir files.
Unfortunately docs don't mention about it, neither any of available themes use this method.

**Comment by dignajar** [comment]
The feature is new, I think nobody is using at this moment, but there are a few ideas to start using it.
I would like to complete the documentation but I don't have the time, for me is better just check the methods of the classes.

**Comment by electron1948** [comment]
Hmmnn... Well I'm trying to use it!    I've just started to try Bludit and got most of a site formatted as I want it but, search as I might I could find no setting anywhere in Settings to display the Logo I had uploaded.  I don't know php, I'm just using the Dashboard.
