### ISSUE TITLE
[CORE] Static pages and categories

### ISSUE THREAD

**Issue by HarleyDavidson86** [bludit/bludit#723]
I can set a category for a static page but the class "Category" does not have a function
to receive all static pages with that category.
So a method like 
`$category->staticPages();`
would be very useful.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
