### ISSUE TITLE
[THEME] Theme settings

### ISSUE THREAD

**Issue by dimobelov** [bludit/bludit#736]
Can we have theme settings like plugin settings?

**Comment by dignajar** [comment]
Yes is possible, meanwhile, you can set variables in the file init.php. Like this theme.
https://github.com/bludit-themes/docs-x/blob/master/init.php

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
