### ISSUE TITLE
Api addons

### ISSUE THREAD

**Issue by liartfr** [bludit/bludit#809]
### Describe your problem
DId it's possible to make the possibility to found page by categories, and tags but with the API, not only the php.

And of course double option : by cat. and by tags for exemple...

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
