### ISSUE TITLE
ADD Calendar

### ISSUE THREAD

**Issue by liartfr** [bludit/bludit#810]
### Describe your problem
I Would like to put an agenda with private view on admin panel (possibility with grant access ) 
and a view from the website for the visitor.

And if , if it's possible of course, the events can have a page to see more information

**Comment by davede-git** [comment]
I like your idea. It would be cool to see also information about posts inside of this calendar, who made it, etc.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
