### ISSUE TITLE
ADD Member page with more info

### ISSUE THREAD

**Issue by liartfr** [bludit/bludit#811]
Hi, i would like to have many case for my member : email, social media, function, phone number, (case we can edit with personnal id, for me instrument of music, and description.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
