### ISSUE TITLE
[CORE/PLUGIN] Additionals SEO fields for Title and H1

### ISSUE THREAD

**Issue by IuseBluditPro** [bludit/bludit#816]
Now is only one field for name page, the same for title page and the same for H1.. 
I need to additional two SEO fields: Title Page (meta title) and for H1. 
Because very often I need to change/add new or different keywords for best SEO of my site. 
Is it possible to add to the core of Bludit, please? 
I need it so much and I think we all need it too.

**Comment by clickwork-git** [comment]
I do not understand your request...

1) The meta title is the title of a page between the tags `<title>` and `</title>`. The formats can be set at **Settings > General > SEO**.

2) The tag `<h1>` is a semantic tag and means, that the title is the most important title of the page. It should not be manipulated: Every word has to be part of the title that is shown on the page.

**Comment by dignajar** [comment]
Hi,
I going to add the field `meta-title`, at the end if you don't complete the field when you create the page is going to take the value from the `title` field.
Regards

**Comment by IuseBluditPro** [comment]
Hi, thank you and when you can finish more or less? 
How I can implement it to the version 3.1 of BluditPro?
If you don't want to add H1 field, Meta-Title = H1.

**Comment by clickwork-git** [comment]
This is nonsense. there is no field `meta-title`, the meta title is `the title between `<title>` and `</title>`:

https://support.google.com/webmasters/answer/79812?hl=en

And there is also no hidden field for `<h1>`:

https://www.hobo-web.co.uk/headers/

**Comment by dimobelov** [comment]
For me there is only one real reason to have these two fields. We know that Google limits the length of the displayed title to 63 characters(now), while for h1 we have no limit. This will allow well-formatted titles to be displayed in both the search engine and in the site itself.

**Comment by Torsten-K** [comment]
@clickwork-git This is no nonsense at all. The title (in the web page’s head) MIGHT be the same as the h1 headline. But sometimes it is more useful to set them differently. The meta title should have max. 64 characters. otherwise it will be shortened/cut off by Google’s search engine. On the contrary, the headline can have characters no matter how many.

So, you could change the theme in a way that the title is not automatically made into a h1 heading. Of course, in this case you’d have to type the heading into the editor (= Simple MDE or TinyMCE).

**Comment by clickwork-git** [comment]
> The meta title should have max. 64 characters.

@Torsten-K As I explained above there is no field meta tag. And: A headline is not a title.

It makes no sense to use tags against their semantic function. Except you would like to be misundertood by search engines, and you are not interested in accessibility.

**Comment by Torsten-K** [comment]
I did not write meta tag but meta title, by which I meant the title in the head section. And again: the title _can_ be the same as the most important headline (h1), but does not have to.

A theme should not turn the name of a page into a title for the HTML head and into a h1 heading as well. Instead, a user should have the opportunity to set the page’s name for the URL (Home), the title (My wonderful website) and the h1 heading (Welcome to my wonderful and frightening website).

So, I think what @IuseBluditPro meant was an opportunity in the backend to set those things manually, if the theme allows.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
