### ISSUE TITLE
Feature request: Date and time for unpublishing a page 

### ISSUE THREAD

**Issue by maiklindner** [bludit/bludit#818]
### Describe your problem

I can not schedule unpublishing times.

### Expected behavior

I need one more field similar to "Date" (with time too) to set a timestamp when the page will disappear.

### Actual behavior

Feature not implemented yet.

### Steps to reproduce the problem

-

### Bludit version

3.1 / 20181008

**Comment by BlakesHeaven** [comment]
Hi, Not wishing to take away from your request, however, you might like to look at my plugin that has just been pushed up today, [Auto-Archive-Menu-Plus-More](https://plugins.bludit.com/plugin/auto-archive).
Hope it helps tide you over.

**Comment by dignajar** [comment]
@maiklindner you some kind of expiration time ?
will dissapear mean deleted ?

I created a ticket a few time ago, https://github.com/bludit/bludit/issues/753

**Comment by Torsten-K** [comment]
@dignajar It should not really be deleted, but only unpublished, so that it is no longer accessible by visitors.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
