### ISSUE TITLE
[CORE][PLUGINS] Add fields to the page settings

### ISSUE THREAD

**Issue by ange007** [bludit/bludit#827]
Are there any hooks/features for adding fields to the settings of a particular entry from the plugin?

**Comment by gmbhurgri** [comment]
@ange007 did you find something ?

**Comment by ange007** [comment]
No :(

**Comment by dignajar** [comment]
This issue is realted to custom fields for pages ? I created a topic about it here, https://github.com/bludit/bludit/issues/895

But not sure if the same case.

**Comment by ange007** [comment]
> This issue is realted to custom fields for pages ? I created a topic about it here, #895
> 
> But not sure if the same case.

Talk about the possibility of a plugin - add settings fields to the post.

**Comment by dignajar** [comment]
From a plugin add a custom field to a post ?
Can you give me an example of use case ?

**Comment by ange007** [comment]
For example, I wanted to screw https://github.com/ange007/poster-gen as a plugin (https://github.com/ange007/bludit-posters). And it would be convenient to give the ability to customize the generator for each post.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
