### ISSUE TITLE
"alt" attribute for Cover Image

### ISSUE THREAD

**Issue by jalediazb** [bludit/bludit#840]
There is no way to add "alt" attribute to cover image.

Bludit version 3.3

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues

**Comment by ChrLau** [comment]
Hi, I would like to see this issue re-opened and addressed as it touches the topic of accessibility.
The change shouldn't be that big and the issue was closed 2 years ago, but there isn't even a Bludit v4 branch yet.
