### ISSUE TITLE
If I rewrite title page,  the url is updated

### ISSUE THREAD

**Issue by jalediazb** [bludit/bludit#841]
I publish a page with a friendly url optimiced. Later, if I rewrite the title, the url change too. In other words, this parameter (friendly url) is not saved.

Thanks.

Bludit version 3.3

**Comment by dimobelov** [comment]
Yes, on 3.3 url is updated on each Title change. This would generate many 404 errors. 
Simple Fix:
https://github.com/bludit/bludit/blob/3510fa6e30416e79e0dfd85f76f6553c606c99c7/bl-kernel/admin/views/edit-content.php#L260
```
                                // Generate slug when the user type the title
				var genSlug = !$("#jsslug").val(); //update only if not exist
				$("#jstitle").keyup(function() {
					var text = $(this).val();
					var parent = $("#jsparent").val();
					var currentKey = "";
					var ajax = new bluditAjax();
					if (genSlug) {
						var callBack = $("#jsslug");
						ajax.generateSlug(text, parent, currentKey, callBack);
					}
				});
```

**Comment by BlakesHeaven** [comment]
Related to automatically changing the 'Friendly URL'; it would be good to be asked if it **should** be changed with a list of internal pages that use the 'Friendly URL', plus a bonus option to ripple through and change them all if you confirm "yes" to change them.

**Comment by dignajar** [comment]
Implemented the idea of @dimobelov.

@BlakesHeaven I don't get the idea of the "list of internal pages that use the friendly url" ?

**Comment by BlakesHeaven** [comment]
By internal pages, I mean, pages within the same website.
For example, a parent page contains a link, e.g. `[Orchestral Masterworks Grand Finale](/2018-sep-to-dec/royal-northern-sinfonia)`, to one of the child pages. This is an internal link.

If the friendly URL changes in the child page because the title was changed, the internal link is currently broken.

So, I was suggesting that if, on changing the child title to "Royal **Southern** Sinfonia" and the friendly URL automatically changes to "royal-**southern**-sinfonia", the link in the other page also changes to `[Orchestral Masterworks Grand Finale](/2018-sep-to-dec/royal-southern-sinfonia)`. that way the link is not broken.
Thanks.

**Comment by dignajar** [comment]
Back to the first issue is solved, I removed the auto update when you are editing the page.
@BlakesHeaven feel free to create an issue with the request to evaluate it. thanks
