### ISSUE TITLE
Some issues with default plugin RSS Feed

### ISSUE THREAD

**Issue by Torsten-K** [bludit/bludit#873]
### Describe your problem

When I activate the default plugin _RSS Feed_  and subscribe to the feed, the title is not shown as headline (which works fine on the website), and no _Read more_-link is shown.

### Expected behavior

See my description.

### Actual behavior

There should be a headline in the feed and a Read-more-link.

### Steps to reproduce the problem

Activate the plugin and subscribe to your own feed. I tested with Thunderbird and Liferea.

### Bludit version

3.4.0

**Comment by dignajar** [comment]
Hi, do you have some RSS as example with the format you mention ? thanks

**Comment by Torsten-K** [comment]
https://www.hin-remscheid.de/news/rss.xml

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
