### ISSUE TITLE
add img and description to Link plugin

### ISSUE THREAD

**Issue by liartfr** [bludit/bludit#881]
### Describe your problem
i would like to create a specific page with the external link but i can't use a picture for that
### Expected behavior
i would like to have a field for img url and field for description.
### Actual behavior
only link and name of this one

**Comment by dignajar** [comment]
Hi,
I don't get the idea, you mean add an link to a picture ?

`<a href="#"><img src="file.jpg"></a>`

**Comment by liartfr** [comment]
yeah , exactly 👍  : 
<a href="$url" title="$title"><img src="$IMG_url"></a>

**Comment by liartfr** [comment]
and eventually link description.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
