### ISSUE TITLE
Wrong path of an image after migration

### ISSUE THREAD

**Issue by clickwork-git** [bludit/bludit#888]
When an installation is migrated to another domain, the absolute path to an image is the one of the old installation (domain).

The cover image has the right path.

**Comment by dignajar** [comment]
Yes this is going to happen because the absolutes URLs are in the content of the pages.
Maybe we need to create a plugin for migrate from one domain to another.

**Comment by sokay** [comment]
Please add this feature. Doing local development and making it a hassle to migrate to a live server.

**Comment by dignajar** [comment]
Hi,
There is a plugin for that https://plugins.bludit.com/plugin/domain-migrator

Also is included in Bludit PRO.
Regards

**Comment by sokay** [comment]
Thanks for point this out!

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues

**Comment by Suleman-Elahi** [comment]
@dignajar Does this plugin can help migrate Bludit from one server to another? I had to move it from one hosting to another. So I zipped all the files from the previous server and extracted to the current server. Only homepage works now, Admin and Posts pages give 404.
