### ISSUE TITLE
[PLUGIN] Thumbnails in OpenGraph and Twitter Cards

### ISSUE THREAD

**Issue by felixplesoianu** [bludit/bludit#898]
### Describe your problem

I would like to request a change in behavior for the OpenGraph and Twitter Card plugins.

### Expected behavior

OpenGraph and Twitter Card plugins should use the thumbnail of a page's featured image, not the full image. Rationale: the thumbnail is smaller, so it loads faster, and that's what it's for in the first place.

### Actual behavior

Both plugins refer to the full image. That slows down loading when pasting the link into e.g. Twitter or Discord, making people wait, and basically hands over the full image to these services without asking.

### Steps to reproduce the problem

1. Enable one or both plugins in a live Bludit installation.
2. Create a page with a featured image.
3. Inspect the generated markup and/or paste a link to the page into a suitable web service.

### Bludit version

3.5

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
