### ISSUE TITLE
with Blog X theme, text moves when you open a post

### ISSUE THREAD

**Issue by ghost** [bludit/bludit#915]
When I enter a post from a post list, like the home page or a category all the page move to the right a bit...

It doesn't happen everywhere, seems related to the lines sizes.

I can not detect what is the pattern for this, but is frequently moving around while i move through categoreies and posts.

I'm using markdown for posts not html. (at the moment without any mark...)

**Comment by dignajar** [comment]
Hi, please complete the questions from the template when you create an issue. Thanks

**Comment by signalguest** [comment]
### Describe your problem
I'm at my first bludit. I turned on the Blog X theme and added 30~ standard posts.
I have few categories wich i used with them.

When i move around in the site, opening posts, opening categories, going back to home page and so on, just moving around in the site, based on i don't know what, maybe lines of the post lenght, all the page move a bit on the right sometimes and somtimes get back to the default position.

### Expected behavior
When I explore the site I except the structure to be static, that the elements are showed in the same exact point.

### Actual behavior
The full page, everything move a bit right or left, based on the content of the page.

### Steps to reproduce the problem
Get a clean Bludit.
Switch to Blog X Theme.
Add pages with categories.
Explore content, in all the way you can find.

### Bludit version
Current.

**Comment by signalguest** [comment]
I tried from scratch.

It's enough to add only 1 post, that have long phrases that go at a new line by themself.

Doing that will move things! And you can see them moving by swapping from the post to the included examples posts in bludit.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
