### ISSUE TITLE
New additions to Bludit user management

### ISSUE THREAD

**Issue by kostaslgr** [bludit/bludit#920]
### Describe your problem
I would like to create a part of the website(not everything) to be accessible only by the users. Also if i give access to someone as Editor, they can edit/delete past posts created by others and this is not desirable.

### Expected behavior & current behaviour
To add a new user role as Reader where they can access these areas of the website that are designed for the members of the website but with no editing powers. I would like them to not be directed to the dashboard after logging in. Also Now there is a plugin(private mode) that can limit access to the whole website. I would like to be able to set the setting to whether this is a private post or a public post, to be done from the page settings.

### Bludit version
3.6.1

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
