### ISSUE TITLE
[PLUGIN,ENHANCEMENT]Sitemap Plugin - external urls addition

### ISSUE THREAD

**Issue by dimobelov** [bludit/bludit#936]
New textarea field to add external urls to generated sitemap(may be separated by new line). 

Description: Often Bludit is used for blog/news section to an existing product with its own pages. Please allow us to add these external links to the generated sitemap.

**Comment by dignajar** [comment]
Sitemap allow external URLs ? I was thinking is only for the same domain/subdomain.

**Comment by dimobelov** [comment]
No, i want to add in sitemap urls from same domain, but external for Bludit.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
