### ISSUE TITLE
Downloading backups does not work because of .htaccess

### ISSUE THREAD

**Issue by ltGuillaume** [bludit/bludit#941]
### Describe your problem
The current .htaccess rule prevents downloading any backups. The location `bl-content/workspaces/backup/` is included in the rule
```
# Deny direct access to the next directories
RewriteRule ^bl-content/(databases|workspaces|pages|tmp)/.*$ - [R=404,L]
```

### Bludit version
3.6.x-3.7.1

**Comment by CarlSeiler** [comment]
Ticket says version 3.6.x-3.7.1. Since this issue is open and I just experienced it in 3.9.1 PRO, is this the same issue or something permissions-based that I can fix?

I'm getting a 404 error from the server on attempting download of the file, and I can see the file exists and has permissions 644. 

While I can download it using FTP, it would be nice to get it from the admin panel.

Thanks
