### ISSUE TITLE
[Suggestion] Editable navbar, new post creation

### ISSUE THREAD

**Issue by Augiiz** [bludit/bludit#947]
Hello, 
I'm here for suggesting some minor improvements for the bludit, which by the way is already great CMS.

The navbar in main theme (and most other themes) adds every single static page that's created. 
Would be nice being able to edit navbar, select which static pages should appear here, and maybe being able to add external link or so.

Talking about static pages, it's very inconvenient going through settings to find option to select post type.
Having Blog post / Static page switcher somewhere in the top (maybe near publish/draft button), would be nice addition.

Thanks, for great CMS, and reading through this suggestion.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
