### ISSUE TITLE
Tag prediction

### ISSUE THREAD

**Issue by davede-git** [bludit/bludit#955]
### Describe your problem
At the moment there is no prediction for tags. It would be great to implement it.

### Expected behavior
I think it would work like "parent" field. You will start to type the tag and Bludit gives you suggestions for existings keywords.

### Actual behavior
none
### Steps to reproduce the problem
???
### Bludit version
3.7.1

**Comment by Joduai** [comment]
would be great if once used tags, were added to clickable list.
I can't remind myself in which cms I've seen similar behaviour.
but it was great, and when it goes to tagging post, too "tagmap" is a disaster when it goes to find similar posts.

**Comment by BlakesHeaven** [comment]
In Bludit v2.3.4 there used to be a very handy list of tags already used that you could just select to use in the content settings:

> ![image](https://user-images.githubusercontent.com/37149377/53300768-3edac600-3843-11e9-8cde-60fd1896c98d.png) ![image](https://user-images.githubusercontent.com/37149377/53300829-e657f880-3843-11e9-8f93-be61fd5cd5e6.png)


`Perhaps this can be brought back again for the next release ... ... ...`

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
