### ISSUE TITLE
content list - additional options for fast management

### ISSUE THREAD

**Issue by Joduai** [bludit/bludit#964]
In my case I base on showing latest post as a sticky on homepage.
For additional styling purposes, and not to mess with list of all posts on paginated subpages.
It's just a much simpler solution than listing posts with conditional statements.

The thing goes to managing the page's options, where I need to uncheck the sticky option in older post.
As the content list contain much free space I'd like to ask for an improvement, to add fast management option for pages on the list like changing page type, category, maybe even tags.
Category and tags would be great for later usage, as blogs tend to get new categories within time, and older post entries sometimes needs to get new tags or get them deleted.

Since bludit's admin panel utilises jquery plugins, I'd also gladly see a feature to change page's position field using jq sortable interactions ( https://jqueryui.com/sortable/ ) There are ready to go plugins afair.
This feature goes to blogs sorting posts by their position instead of creation date.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
