### ISSUE TITLE
[Suggestion] Ctrl+S to save post in editor

### ISSUE THREAD

**Issue by Blukzen** [bludit/bludit#989]
It would be nice to be able to Ctrl+S to save the current post in the editor especially when using a fullscreen editor like SimpleMDE.

**Comment by Joduai** [comment]
Ajax like save option without reloading page would also come in hand. Especially during long posts edition,

**Comment by dignajar** [comment]
I like the idea, but is hard with the current approach, POST method.
I'm working in the API to start doing everything via AJAX, also the admin panel can be via AJAX.

**Comment by dignajar** [comment]
Hello, with the new version of Bludit v4.0 rc1, I would like to close the old Github issues. If you feel that your issue is not resolved in the latest version, create a new ticket.

- Help and Support use the Forum https://forum.bludit.org
- Bugs and new requests here in Github https://github.com/bludit/bludit/issues
