### ISSUE TITLE
file_get_contents not working inside plugin.php

### ISSUE THREAD

**Issue by philippd1** [bludit/bludit#990]
I'm trying to parse the latest Bludit Build from the stable release channel from https://version.bludit.com/ with PHP.
But getting the required data from the URL isn't possible inside the Bludit plugin page.
```
<?php
$urlData = file_get_contents("https://version.bludit.com/");
echo $urlData;
?>
```
this block of code is working when testing inside a blank php file, but not loaded inside of my ./plugin.php
also, no errors, warnings or other php logs are thrown.

any help would be appreciated😊

**Comment by SamBrishes** [comment]
Hellow,

is the code above the full content of your `plugin.php` file? I'm asking because the Plugin API of Bludit is OOP (Object-Oriented), so you need to define a class, which extends the Plugin class. Otherwise the code is executed at any time, even if the plugin is disabled.

You can try the following code, it works on my environment with the latest Bludit version (It should print the JSON response, but only if the plugin is enabled, of course):

```php
<?php

    class BluditVersionPlugin extends Plugin{

        public function beforeAdminLoad(){
            $urlData = file_get_contents("https://version.bludit.com/");
            echo $urlData;
        }

    }
```

However, I would not recommend `file_get_contents` for such purposes, because it doesn't work on each environment. (The function depends on the `allow_url_fopen` php.ini option, which is theoretically enabled per default but many hoster and webspaces disable it for security reasons). It's maybe better to use the [`cURL` library](http://php.net/manual/de/function.curl-init.php), which is build for this (It is also way faster compared to `file_get_contents`).

A cURL example: 

```php
<?php

    class BluditVersionPlugin extends Plugin{

        public function beforeAdminLoad(){
            $curl = curl_init();
            curl_setopt($curl, CURLOPT_URL, "https://version.bludit.com");
            curl_setopt($curl, CURLOPT_HEADER, false);
            curl_setopt($curl, CURLOPT_TIMEOUT, 60);
            curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($curl, CURLOPT_FOLLOWLOCATION, true);
            curl_setopt($curl, CURLOPT_HTTPHEADER, array(
               "Content-Type: application/json"
            ));
            $content = curl_exec($curl);
            $response = curl_getinfo($curl, CURLINFO_HTTP_CODE);
            curl_close($curl);

            // Response
            if($response != 200){
               return false;
            }
            var_dump(json_decode($content, true));
        }
        
    }
```

Sincerely,
Sam.

**Comment by philippd1** [comment]
thanks for the hint to cURL, Sam
I'm struggling with the implementation of getting data from another url tho, just like in #994 
think we can maybe solve both of these issues at once :)

**Comment by naplaya** [comment]
you have to do it like this, defining an agent

```    
$opts = ['http' => ['method' => 'GET','header' => ['User-Agent: PHP']]];
$context = stream_context_create($opts);
$content = file_get_contents($base_url, false, $context);
```

**Comment by philippd1** [comment]
thanks for the suggestion, I will see what I can do tomorrow👊

**Comment by philippd1** [comment]
```
<?php
class autoUpdater extends Plugin{
	public function init(){
		$this->formButtons = false;
	}
	public function form(){
		$html = '<label>This plugin automatically downloads and installs the latest Bludit version offered on the official Bludit site.<br><b>Warning:</b> This will overwrite your bludit installation.</label>';
		
		$html .= '<br>Current Bludit Version: '.BLUDIT_VERSION.'<br>Current Bludit Build: '.BLUDIT_BUILD.'<br>';

		// get latest version
		
		$opts = ['http' => ['method' => 'GET','header' => ['User-Agent: PHP']]];
		$context = stream_context_create($opts);
		$content = file_get_contents("https://version.bludit.com/", false, $context);
		$html .= "[".$content."]";//NOTHING


		$html .= "<br>";
		
		$content = file_get_contents("https://version.bludit.com/");
		$html .= "[".$content."]";//NOTHING
		
		$html .= "<br>";

		// compare installed build to latest build

		$html .= '<a class="btn btn-primary">update Bludit now</a>';//only show this if bludit version is old
		
		return $html;
	}
}
?>
```

@naplaya I really don't know why, but none of the mentioned methods are working for me...
full code @https://github.com/philippd1/bludit-auto-update/tree/dev

**Comment by philippd1** [comment]
Okay...
so apparently the issue this whole time was a tiny issue in my localhost server setup...
I'm sorry for the confusion and thanks for all of your help!
