### ISSUE TITLE
Request: Control `allowComments` Page Option

### ISSUE THREAD

**Issue by ghost** [bludit/bludit#993]
Hellow,

We noticed [here](https://github.com/pytesNET/snicker/issues/1#issuecomment-472568663) that the pages database contains a `allowComments` variable / option, which cannot be changed on the `new-content.php` nor the `edit-content.php` bludit administration pages. However, such an option would be really really helpful for custom comment plugins.

A simple implementation like the following one (which works at least on the latest version) would be perfect. (Example code for `edit-content.php`)

```php
// Page Comments
echo Bootstrap::formSelectBlock(array(
    'name'      => 'allowComments',
    'label'     => $L->g('Page Comments'),
    'selected'  => $page->allowComments()? "1": "0",
    'class'     => '',
    'options'   => array(
        "1"     => $L->g('Allow Comments'),
        "0"     => $L->g('Disallow Comments')
    )
));
```

Thanks.

Sincerely,
Sam.

**Comment by dignajar** [comment]
Hi,
yes I need to check this, the problem is provided this button to change this field when the user don't have enabled a comment system, is going to be wired.

I was thinking to add to the plugins a field `type`, so if the plugin is related to a comment system has the `type=comments`, if the plugin is an HTML Editor the type is `editor`, so is possible to check if there are some plugin enabled with the type `comments` so appear this checkbox.

**Comment by dignajar** [comment]
Related topic: https://github.com/bludit/bludit/issues/996

**Comment by DivineDominion** [comment]
So you plan to conditionally show the `allowComments` checkbox if a comment-type plugin is enabled? I think that could work, but I'm not sure if a strict taxonomy like #996 proposes is useful in the long run. Why not add additional hooks, so that plugins can e.g. in the constructor tell the system which capabilities they require/want to enable?
