### ISSUE TITLE
Include to the plugins a field type

### ISSUE THREAD

**Issue by dignajar** [bludit/bludit#996]
Include to the plugin metadata a field `type`.
The type could be for:
- Markdown Editor = `markdown-editor`
- WYSIWYG Editor = `wysiwyg-editor`
- Comment system = `comments`
- Stats, visitors, counters, Analytics = `analytics`

With this approach is possible to identify if there are some plugin enabled for the Editor or if there are some comment system enabled.

**Comment by SamBrishes** [comment]
Hellow,

that's a really good idea, but will it also be possible to define multiple types per plugin (maybe as comma-separated list or array)? Because it may restrict the plugin authors by forcing a KISS-styled environment (So one task / type per plugin).

Another solution would be an additional (static) registration of available plugin functionalities. Just thinking out loud, something like

```php
class MyPlugin extens Plugin{
    
    /*
     |  INIT HOOK
     */
    public function __init(){
        self::addSupport("comments");
        self::addSupport("markup-editor");
        self::addSupport("analytics");
    }
}

//[...]

if(Plugin::hasSupport("comments") === true){
    var_dump(Plugin::getSupported("comments")); 
    // Returns an array with plugins which supports this function.
}
```

It's just an idea.

Sincerely,
Sam.

**Comment by BlakesHeaven** [comment]
Mabe this is already covered, but if a plugin is developed that does not fit in with any type in the list there should be an easy way to add a new type via admin that becomes available if the plugin is installed by others.
